### ISSUE TITLE
Instgramに自動ログイン

### ISSUE THREAD

**Issue by subarunrun0812** [subarunrun0812/python_automation_contest_2days#1]

**Comment by yuto1009** [comment]
自動ログインで参考にしたサイト(seleniumの入れ方)<できなかった>
instagram自動ログインサンプルコードあり
https://self-development.info/instagram%E3%81%AB%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%A7%E8%87%AA%E5%8B%95%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E3%81%99%E3%82%8B%E3%80%90python-selenium%E3%80%91/

instaloaderの使い方　ユーザー情報（フォロー数・フォロワー数・投稿ポスト数の取得）<使用可能>
https://qiita.com/MOSO1409/items/1c119f6d31e345410b91

instaloaderのレポジトリ
https://github.com/instaloader/instaloader

**Comment by yuto1009** [comment]
自動ログインに使用しているライブラリ<Playwright>
使用コードソース
https://stackoverflow.com/questions/73378427/how-to-scrape-the-instagram-followers-popup-with-python-playwright
